import { describe, it, expect } from "vitest";
import { render, screen, fireEvent, within } from "@testing-library/react";
import React from "react";
import { MemoryRouter } from "react-router-dom";
import { ReportsPage } from "../../src/pages/ReportsPage.js";

function renderReports() {
  return render(
    <MemoryRouter>
      <ReportsPage />
    </MemoryRouter>,
  );
}

describe("ReportsPage", () => {
  it("renders the Reports sidebar heading and Reviewer history subtitle", () => {
    renderReports();
    expect(screen.getByText("Reports")).toBeDefined();
    expect(screen.getByText("Reviewer history")).toBeDefined();
  });

  it("renders all three mock reports in the list", () => {
    renderReports();
    expect(screen.getByText("Apr 6, 2026")).toBeDefined();
    expect(screen.getByText("Apr 5, 2026")).toBeDefined();
    expect(screen.getByText("Apr 4, 2026")).toBeDefined();
  });

  it("renders the first report as the default selected detail view", () => {
    renderReports();
    expect(screen.getByText(/Weekly Review · Apr 6, 2026/)).toBeDefined();
    expect(
      screen.getByText(/Generated by Reviewer · claude-sonnet-4-6/),
    ).toBeDefined();
    expect(screen.getByText("7d Net PnL")).toBeDefined();
    expect(screen.getByText("+$127.50")).toBeDefined();
    expect(screen.getByText("62.5%")).toBeDefined();
    expect(screen.getByText("15 / 24 trades")).toBeDefined();
    expect(screen.getByText("1.42")).toBeDefined();
  });

  it("renders the bucket table with mock bucket rows for the default report", () => {
    renderReports();
    expect(screen.getByText("Per-bucket performance")).toBeDefined();
    expect(screen.getByText("0.40")).toBeDefined();
    expect(screen.getByText("71.4%")).toBeDefined();
    expect(screen.getByText("+$56.20")).toBeDefined();
  });

  it("renders reviewer notes and filter proposals for the default report", () => {
    renderReports();
    expect(screen.getByText("Notes from Reviewer")).toBeDefined();
    expect(
      screen.getByText(/Bucket 0\.40-0\.45 was the standout performer/),
    ).toBeDefined();
    expect(screen.getByText("Filter proposals")).toBeDefined();
    expect(screen.getByText("min_net_flow_1m")).toBeDefined();
    expect(screen.getByText("min_unique_traders_1m")).toBeDefined();
    expect(screen.getByText("take_profit_pct")).toBeDefined();
  });

  it("switches the detail view when a different report is clicked", () => {
    renderReports();
    fireEvent.click(screen.getByText("Apr 4, 2026"));
    expect(screen.getByText(/Daily Review · Apr 4, 2026/)).toBeDefined();
    expect(screen.getByText("(no notes)")).toBeDefined();
    expect(
      screen.getByText(/No filter proposals for this report/),
    ).toBeDefined();
    expect(
      screen.getByText(/No bucket data for this report/),
    ).toBeDefined();
  });

  it("renders the Sidebar navigation with pending proposal badge", () => {
    renderReports();
    const nav = screen.getByRole("navigation");
    expect(within(nav).getByText(/Reports/)).toBeDefined();
    expect(within(nav).getByText("2")).toBeDefined();
  });
});
