"""Signal analyzer using LLM for trading signal analysis."""

import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional, Any
from uuid import UUID, uuid4

from .event_bus import EventBus, EventType, Event


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"
    MODIFY_RISK = "modify_risk"
    NONE = "none"


class ConfidenceLevel(Enum):
    """Confidence levels for signals."""
    VERY_HIGH = 5
    HIGH = 4
    MEDIUM = 3
    LOW = 2
    VERY_LOW = 1


@dataclass
class MarketContext:
    """Market context for signal analysis."""
    market_id: str
    symbol: str
    current_price: Decimal
    bid: Decimal
    ask: Decimal
    spread: Decimal
    spread_percent: Decimal

    # Market data
    volume_24h: Decimal
    volume_change_24h: Decimal
    price_change_24h: Decimal
    price_change_percent_24h: Decimal

    # Order book
    bid_depth: Decimal
    ask_depth: Decimal
    order_book_imbalance: Decimal

    # Market conditions
    volatility: Optional[Decimal] = None
    trend: Optional[str] = None  # "up", "down", "sideways"
    market_phase: Optional[str] = None  # "accumulation", "markup", "distribution", "markdown"


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    signal_id: str
    signal_type: SignalType
    market_id: str
    symbol: str

    # Signal details
    side: str  # "yes" or "no"
    confidence: Decimal  # 0 to 1
    urgency: str  # "immediate", "normal", "low"

    # Pricing
    suggested_entry: Decimal
    suggested_exit: Decimal
    stop_loss: Decimal
    take_profit: Decimal
    risk_reward_ratio: Decimal

    # Size
    suggested_size: Decimal
    max_risk_amount: Decimal
    position_percentage: Decimal

    # Reasoning
    signal_reason: str
    technical_factors: List[str]
    fundamental_factors: List[str]
    sentiment_factors: List[str]

    # Context
    market_context: MarketContext
    timestamp: datetime
    expires_at: Optional[datetime] = None

    # Metadata
    source: str = "system"
    strategy_id: Optional[str] = None
    correlation_id: str = ""


@dataclass
class AnalysisResult:
    """Result of signal analysis."""
    signal_id: str
    approved: bool
    action: str  # "execute", "modify", "reject", "delay"

    # Modified parameters (if action == "modify")
    modified_entry: Optional[Decimal] = None
    modified_exit: Optional[Decimal] = None
    modified_size: Optional[Decimal] = None
    modified_stop_loss: Optional[Decimal] = None
    modified_take_profit: Optional[Decimal] = None

    # Analysis details
    approval_reason: str = ""
    rejection_reason: str = ""
    risk_score: Decimal = Decimal("0")
    confidence_adjustment: Decimal = Decimal("0")

    # Additional checks
    risk_checks_passed: bool = False
    portfolio_checks_passed: bool = False
    market_checks_passed: bool = False

    # LLM analysis
    llm_analysis: Optional[Dict[str, Any]] = None
    llm_confidence: Optional[Decimal] = None

    timestamp: datetime = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()


class LLMClient(ABC):
    """Abstract LLM client for signal analysis."""

    @abstractmethod
    async def analyze_signal(
        self,
        signal: Signal,
        portfolio_context: Dict[str, Any],
        historical_signals: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Analyze signal using LLM.

        Returns:
            Dict with keys:
            - approved: bool
            - confidence: float
            - reasoning: str
            - risk_assessment: dict
            - suggested_modifications: dict (optional)
        """
        pass


class RiskChecker:
    """Risk checker for signal validation."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.max_daily_loss = Decimal(config.get("max_daily_loss", "0.02"))
        self.max_weekly_loss = Decimal(config.get("max_weekly_loss", "0.04"))
        self.max_single_position = Decimal(config.get("max_single_position", "0.25"))
        self.max_total_exposure = Decimal(config.get("max_total_exposure", "0.80"))

    async def check_risk(
        self,
        signal: Signal,
        portfolio_context: Dict[str, Any],
    ) -> tuple[bool, str]:
        """Check if signal passes risk criteria.

        Returns:
            (passed, reason)
        """
        # Check daily loss limit
        daily_pnl = portfolio_context.get("daily_pnl", Decimal("0"))
        if daily_pnl < 0:
            daily_loss_pct = abs(daily_pnl) / portfolio_context.get("initial_balance", Decimal("1"))
            if daily_loss_pct >= self.max_daily_loss:
                return False, f"Daily loss limit exceeded: {daily_loss_pct:.2%}"

        # Check position size
        position_pct = signal.position_percentage
        if position_pct > self.max_single_position:
            return False, f"Position size too large: {position_pct:.2%} > {self.max_single_position:.2%}"

        # Check max exposure
        current_exposure = portfolio_context.get("current_exposure", Decimal("0"))
        if current_exposure + position_pct > self.max_total_exposure:
            return False, f"Max exposure would be exceeded"

        # Check stop loss
        if signal.stop_loss <= 0:
            return False, "Invalid stop loss price"

        # Calculate max risk
        risk_amount = abs(signal.suggested_entry - signal.stop_loss) * signal.suggested_size
        if risk_amount > signal.max_risk_amount:
            return False, f"Risk amount {risk_amount} exceeds max {signal.max_risk_amount}"

        return True, "All risk checks passed"


class PortfolioChecker:
    """Portfolio checker for signal validation."""

    async def check_portfolio(
        self,
        signal: Signal,
        portfolio_context: Dict[str, Any],
    ) -> tuple[bool, str]:
        """Check if signal is compatible with portfolio state.

        Returns:
            (passed, reason)
        """
        # Check trading mode
        if portfolio_context.get("trading_mode") == "paper":
            # Paper trading can proceed
            pass
        elif portfolio_context.get("trading_mode") == "live":
            # Live trading needs additional checks
            if not portfolio_context.get("live_trading_enabled"):
                return False, "Live trading not enabled for this portfolio"

        # Check available balance
        available_balance = portfolio_context.get("available_balance", Decimal("0"))
        required_margin = signal.suggested_entry * signal.suggested_size

        if available_balance < required_margin:
            return False, f"Insufficient balance: {available_balance} < {required_margin}"

        # Check max positions
        open_positions = portfolio_context.get("open_positions_count", 0)
        max_positions = portfolio_context.get("max_open_positions", 10)
        if open_positions >= max_positions:
            return False, f"Max open positions reached: {open_positions}/{max_positions}"

        # Check existing position in same market
        market_id = signal.market_id
        existing_position = portfolio_context.get("positions", {}).get(market_id)
        if existing_position:
            # Check if adding to position or reversing
            existing_side = existing_position.get("side")
            if existing_side == signal.side:
                return True, "Adding to existing position"
            else:
                return True, "Reversing position"

        return True, "Portfolio checks passed"


class MarketChecker:
    """Market condition checker for signal validation."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.min_liquidity = Decimal(config.get("min_liquidity", "10000"))
        self.max_spread_percent = Decimal(config.get("max_spread_percent", "0.02"))
        self.dead_zone_low = Decimal(config.get("dead_zone_low", "0.40"))
        self.dead_zone_high = Decimal(config.get("dead_zone_high", "0.60"))

    async def check_market(
        self,
        signal: Signal,
    ) -> tuple[bool, str]:
        """Check if market conditions are suitable for trading.

        Returns:
            (passed, reason)
        """
        context = signal.market_context

        # Check liquidity
        if context.volume_24h < self.min_liquidity:
            return False, f"Insufficient liquidity: {context.volume_24h} < {self.min_liquidity}"

        # Check spread
        if context.spread_percent > self.max_spread_percent:
            return False, f"Spread too wide: {context.spread_percent:.4%} > {self.max_spread_percent:.2%}"

        # Check price in dead zone
        current_price = float(context.current_price)
        if self.dead_zone_low < current_price < self.dead_zone_high:
            return False, f"Price in dead zone: {current_price}"

        # Check market volatility
        if context.volatility and context.volatility > Decimal("0.5"):
            return False, f"Market too volatile: {context.volatility}"

        return True, "Market conditions suitable"


class SignalAnalyzer:
    """Main signal analyzer that coordinates all checks and LLM analysis."""

    def __init__(
        self,
        event_bus: EventBus,
        llm_client: Optional[LLMClient] = None,
        config: Optional[Dict[str, Any]] = None,
    ):
        self.event_bus = event_bus
        self.llm_client = llm_client
        self.config = config or {}

        # Initialize checkers
        self.risk_checker = RiskChecker(self.config.get("risk", {}))
        self.portfolio_checker = PortfolioChecker()
        self.market_checker = MarketChecker(self.config.get("market", {}))

        # Subscribe to signal events
        self._unsubscribe = None

    async def start(self) -> None:
        """Start the analyzer."""
        self._unsubscribe = self.event_bus.subscribe(
            EventType.SIGNAL_GENERATED,
            self._handle_signal,
        )

    async def stop(self) -> None:
        """Stop the analyzer."""
        if self._unsubscribe:
            self._unsubscribe()
            self._unsubscribe = None

    async def _handle_signal(self, event: Event) -> None:
        """Handle incoming signal event."""
        signal_data = event.payload

        # Convert to Signal object
        signal = self._parse_signal(signal_data)

        # Analyze signal
        result = await self.analyze(signal)

        # Publish result
        result_event = self.event_bus.create_event(
            event_type=EventType.SIGNAL_ANALYZED,
            source="analyzer",
            payload=self._serialize_result(result),
        )

        if result.approved:
            await self.event_bus.publish(EventType.SIGNAL_APPROVED, result_event)
        else:
            await self.event_bus.publish(EventType.SIGNAL_REJECTED, result_event)

    def _parse_signal(self, data: Dict[str, Any]) -> Signal:
        """Parse signal from event payload."""
        # Implementation depends on exact structure
        # This is a simplified version
        return Signal(
            signal_id=data.get("signal_id", str(uuid4())),
            signal_type=SignalType(data.get("signal_type", "buy")),
            market_id=data["market_id"],
            symbol=data["symbol"],
            side=data["side"],
            confidence=Decimal(str(data.get("confidence", "0.5"))),
            urgency=data.get("urgency", "normal"),
            suggested_entry=Decimal(str(data["suggested_entry"])),
            suggested_exit=Decimal(str(data.get("suggested_exit", "0"))),
            stop_loss=Decimal(str(data.get("stop_loss", "0"))),
            take_profit=Decimal(str(data.get("take_profit", "0"))),
            risk_reward_ratio=Decimal(str(data.get("risk_reward_ratio", "0"))),
            suggested_size=Decimal(str(data["suggested_size"])),
            max_risk_amount=Decimal(str(data.get("max_risk_amount", "0"))),
            position_percentage=Decimal(str(data.get("position_percentage", "0"))),
            signal_reason=data.get("signal_reason", ""),
            technical_factors=data.get("technical_factors", []),
            fundamental_factors=data.get("fundamental_factors", []),
            sentiment_factors=data.get("sentiment_factors", []),
            market_context=MarketContext(
                market_id=data["market_id"],
                symbol=data["symbol"],
                current_price=Decimal(str(data["market_context"]["current_price"])),
                bid=Decimal(str(data["market_context"]["bid"])),
                ask=Decimal(str(data["market_context"]["ask"])),
                spread=Decimal(str(data["market_context"]["spread"])),
                spread_percent=Decimal(str(data["market_context"]["spread_percent"])),
                volume_24h=Decimal(str(data["market_context"]["volume_24h"])),
                volume_change_24h=Decimal(str(data["market_context"]["volume_change_24h"])),
                price_change_24h=Decimal(str(data["market_context"]["price_change_24h"])),
                price_change_percent_24h=Decimal(str(data["market_context"]["price_change_percent_24h"])),
                bid_depth=Decimal(str(data["market_context"]["bid_depth"])),
                ask_depth=Decimal(str(data["market_context"]["ask_depth"])),
                order_book_imbalance=Decimal(str(data["market_context"]["order_book_imbalance"])),
            ),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            expires_at=datetime.fromisoformat(data["expires_at"]) if data.get("expires_at") else None,
            source=data.get("source", "system"),
            strategy_id=data.get("strategy_id"),
        )

    def _serialize_result(self, result: AnalysisResult) -> Dict[str, Any]:
        """Serialize analysis result to dict."""
        return {
            "signal_id": result.signal_id,
            "approved": result.approved,
            "action": result.action,
            "modified_entry": str(result.modified_entry) if result.modified_entry else None,
            "modified_exit": str(result.modified_exit) if result.modified_exit else None,
            "modified_size": str(result.modified_size) if result.modified_size else None,
            "modified_stop_loss": str(result.modified_stop_loss) if result.modified_stop_loss else None,
            "modified_take_profit": str(result.modified_take_profit) if result.modified_take_profit else None,
            "approval_reason": result.approval_reason,
            "rejection_reason": result.rejection_reason,
            "risk_score": str(result.risk_score),
            "confidence_adjustment": str(result.confidence_adjustment),
            "risk_checks_passed": result.risk_checks_passed,
            "portfolio_checks_passed": result.portfolio_checks_passed,
            "market_checks_passed": result.market_checks_passed,
            "timestamp": result.timestamp.isoformat(),
        }

    async def analyze(self, signal: Signal) -> AnalysisResult:
        """Analyze a trading signal."""
        # Fetch portfolio context
        portfolio_context = await self._fetch_portfolio_context(signal)

        # Run checks
        risk_passed, risk_reason = await self.risk_checker.check_risk(signal, portfolio_context)
        portfolio_passed, portfolio_reason = await self.portfolio_checker.check_portfolio(signal, portfolio_context)
        market_passed, market_reason = await self.market_checker.check_market(signal)

        # If any check fails, reject immediately
        if not all([risk_passed, portfolio_passed, market_passed]):
            reasons = []
            if not risk_passed:
                reasons.append(f"Risk: {risk_reason}")
            if not portfolio_passed:
                reasons.append(f"Portfolio: {portfolio_reason}")
            if not market_passed:
                reasons.append(f"Market: {market_reason}")

            return AnalysisResult(
                signal_id=signal.signal_id,
                approved=False,
                action="reject",
                rejection_reason="; ".join(reasons),
                risk_checks_passed=risk_passed,
                portfolio_checks_passed=portfolio_passed,
                market_checks_passed=market_passed,
            )

        # If all checks pass, optionally use LLM for final analysis
        llm_result = None
        if self.llm_client:
            historical_signals = await self._fetch_historical_signals(signal)
            llm_result = await self.llm_client.analyze_signal(
                signal,
                portfolio_context,
                historical_signals,
            )

            # Override approval based on LLM
            if not llm_result.get("approved", True):
                return AnalysisResult(
                    signal_id=signal.signal_id,
                    approved=False,
                    action="reject",
                    rejection_reason=llm_result.get("reasoning", "LLM rejected signal"),
                    risk_checks_passed=True,
                    portfolio_checks_passed=True,
                    market_checks_passed=True,
                    llm_analysis=llm_result,
                )

        # Approve signal
        result = AnalysisResult(
            signal_id=signal.signal_id,
            approved=True,
            action="execute",
            approval_reason="All checks passed",
            risk_checks_passed=True,
            portfolio_checks_passed=True,
            market_checks_passed=True,
            llm_analysis=llm_result,
        )

        # Apply LLM modifications if any
        if llm_result and llm_result.get("suggested_modifications"):
            mods = llm_result["suggested_modifications"]
            result.action = "modify"
            result.modified_entry = Decimal(str(mods.get("entry", signal.suggested_entry)))
            result.modified_size = Decimal(str(mods.get("size", signal.suggested_size)))
            result.modified_stop_loss = Decimal(str(mods.get("stop_loss", signal.stop_loss)))
            result.modified_take_profit = Decimal(str(mods.get("take_profit", signal.take_profit)))

        return result

    async def _fetch_portfolio_context(self, signal: Signal) -> Dict[str, Any]:
        """Fetch portfolio context for signal analysis."""
        # This would typically fetch from database
        # For now, return placeholder
        return {
            "portfolio_id": signal.correlation_id,
            "initial_balance": Decimal("10000"),
            "available_balance": Decimal("8000"),
            "daily_pnl": Decimal("0"),
            "open_positions_count": 0,
            "positions": {},
            "trading_mode": "paper",
            "live_trading_enabled": False,
        }

    async def _fetch_historical_signals(self, signal: Signal) -> List[Dict[str, Any]]:
        """Fetch historical signals for LLM context."""
        # Placeholder - would fetch from database
        return []


def create_analyzer(
    event_bus: EventBus,
    llm_client: Optional[LLMClient] = None,
    config: Optional[Dict[str, Any]] = None,
) -> SignalAnalyzer:
    """Create and configure a signal analyzer."""
    return SignalAnalyzer(event_bus, llm_client, config)
